### ISSUE TITLE
Content Revision for 113A

### ISSUE THREAD

**Issue by bruce88617** [bruce88617/nycudopcs#9]
## 重新整理內容

- 是否要調整? 哪些要刪除或移至下學期? 哪些要增加?

**Comment by yaio4109** [comment]
有一個網頁式的講義，可以方便跳轉各個Lecture或搜索上課內容，你覺得會提升你跟學生的上課品質嗎~

如果覺得會的話，我可以用[Jupyter book](https://jupyterbook.org/en/stable/start/your-first-book.html)把當下已經弄好的lecture.ipynb快速的弄成一個網頁，然後再用github page把這個網頁弄出來就好

**Comment by bruce88617** [comment]
我覺得可以，我研究看看

**Comment by bruce88617** [comment]
First push for jupyter book. Still have some bugs to publish as a GitHub pages.

**Comment by bruce88617** [comment]
> First push for jupyter book. Still have some bugs to publish as a GitHub pages.

Deployed: [here](https://bruce88617.github.io/nycudopcs_jb/chapters/intro.html)
